# Configuration for Alacritty, the GPU enhanced terminal emulator.

#import:
#  - /path/to/alacritty.yml

window:
  dimensions:
    columns: 90
    lines: 30

  padding:
    x: 1
    y: 1

  dynamic_padding: true

  # Window decorations
  # Values: none, full, transparent, buttonless
  decorations: full

  #title: Alacritty

  dynamic_title: true

font:
  normal: 
    family: &font-family Fantasque Sans Mono
    style: Regular

  bold:
    family: *font-family
    style: Regular

  italic:
    family: *font-family
    style: Italic

  size: 12.5

  # Offset is the extra space around each character.
  offset:
    x: 1
    y: 0

  #glyph_offset:
  #  x: 0
  #  y: 0

  # Thin stroke font rendering (macOS only)
  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: true

schemes:
  gruvbox: &gruvbox
    primary:
      hard-contrast: &hard '#1d2021'
      okay-contrast: &okay '#282828'
      soft-contrast: &soft '#32302f'

      background: *okay
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

colors: *gruvbox
  #cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  #vi_mode_cursor:
  #  text: CellBackground
  #  cursor: CellForeground
  #  background: CellForeground

  #search:
    #matches:
    #  foreground: '#000000'
    #  background: '#ffffff'
    #focused_match:
    #  foreground: CellBackground
    #  background: CellForeground

    #bar:
    #  background: '#c5c8c6'
    #  foreground: '#1d1f21'

#background_opacity: 1.0

selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  vi_mode_style: None

  unfocused_hollow: true

  #thickness: 0.15

#shell:
#  program: /bin/zsh
#  args:
#    - --login

#working_directory: None

# Send ESC (\x1b) before characters when alt is pressed.
#alt_send_esc: true

#debug:
  # Display the time it takes to redraw each frame.
  #render_timer: false

  # Keep the log file after quitting Alacritty.
  #persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - None
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  #log_level: Warn

  # Print all received window events.
  #print_events: false
