# Configuration for Alacritty, the GPU enhanced terminal emulator.

#import:
#  - /path/to/alacritty.yml

window:
  dimensions:
    columns: 90
    lines: 26

  padding:
    x: 1
    y: 1

  dynamic_padding: true

  # Window decorations
  # Values: none, full, transparent, buttonless
  decorations: full

  #title: Alacritty

  dynamic_title: true

font:
  normal: 
    family: &font-family JetBrains Mono NL
    #style: Regular

  bold:
    family: *font-family
    #style: Regular

  italic:
    family: *font-family
    #style: Italic

  size: 12

  # Offset is the extra space around each character.
  offset:
    x: 1
    y: 0

  #glyph_offset:
  #  x: 0
  #  y: 0

  # Thin stroke font rendering (macOS only)
  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: true
schemes:
  onedark: &onedark
    # Default colors
    primary:
      foreground: '0xabb2bf'
      background: '0x282c34'

    # Cursor colors
    cursor:
      text: '0x5c6370'
      cursor: '0xabb2bf'

    # Normal colors
    normal:
      black:   '0x5c6370'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xe5c07b'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0xabb2bf'

    # Bright colors
    bright:
      black:   '0x4b5263'
      red:     '0xbe5046'
      green:   '0x98c379'
      yellow:  '0xd19a66'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0x3e4452'

colors: *onedark
  #cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  #vi_mode_cursor:
  #  text: CellBackground
  #  cursor: CellForeground
  #  background: CellForeground

  #search:
    #matches:
    #  foreground: '#000000'
    #  background: '#ffffff'
    #focused_match:
    #  foreground: CellBackground
    #  background: CellForeground

    #bar:
    #  background: '#c5c8c6'
    #  foreground: '#1d1f21'

#background_opacity: 1.0

selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  vi_mode_style: None

  unfocused_hollow: true

  #thickness: 0.15

#shell:
#  program: /bin/zsh
#  args:
#    - --login

#working_directory: None

# Send ESC (\x1b) before characters when alt is pressed.
#alt_send_esc: true

#debug:
  # Display the time it takes to redraw each frame.
  #render_timer: false

  # Keep the log file after quitting Alacritty.
  #persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - None
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  #log_level: Warn

  # Print all received window events.
  #print_events: false

